#+TITLE: Eddy diffusivity from microstructure

* Todo [3/15]
- [ ] equations for mixed layer

eddydiff:
- [X] calculate sigma_0 and rho for Argo/ECCO
- [X] linear fit to ρ in bins to get dTiso
  - too low!
- [ ] do I choose bins from ECCO rho instead of transect rho?
- [ ] dTdz by fitting T vs P in isopycnal bin?
- [ ] make complicated plot:
  - [ ] given bins, show TS, Trms, Ke
  - [ ] compare mean T,S, ρ profile from transect and climatology?
- [ ] Kt for P06 is too high! Tell Jonathan
  - OK results if I filter out high values
- [ ] Do hann smoother for mean field. I think the spline screws up near the edges
  - I need a "natural interpolating B-spline". scipy doesn't seem to have this.
  - NG2016 seems to have this problem.

- [ ] figure out resolution : GO-SHIP spacing + ECCO (1°)

- [ ] compare transect mean field to ECCO/Argo means

- [ ] argo monthly gradients - need to average properly!

- [ ] use MIMOC
- [ ] properly calculate gradients from mean fields.
  - [ ] PCHIP?
  - [ ] what are people doing for vertical smoothing?
- [X] maybe the strong seasonal cycle means that the annual mean is useless?
  - no, that doesn't help much either

- [-] Do bob ctd chipod [4/5]
  - [ ] Why is dTm/dz >> dT/dz
  - [X] Read in emily's data + convert to xarray
  - [X] Average turbulence data as needed
  - [X] Determine sample points for gradients
  - [X] sign error in dTdz?

* Datasets

- [X] Cole et al.
- [X] Gnanadesikan
- [X] Abernathey
- [X] Roach: https://github.com/croachutas/Isopycnal_Diffusivity
- [X] Groeskamp

* Conventions
1. Climatology name: ~clim.attrs.dataset~
2. Transect name : ~transect.transect_name~
3. Potential density referenced to 0: currently ~rho~, should be ~sigma_0~
4. in-situ density: currently unused, should be ~rho~
5. ~pres~ is local pressure (dbar), ~P~ is technically co-ordinate. Especially important for BoB xpod!

* Finestructure work
Things to try:
1. Make sure that 200m smoothing is the problem.
   a. [ ] Construct 200m averages of microstructure quantities for each profile and then do the estimate
   b. [ ] Do the finestructure estimate on NATRE profiles and try again

2. What if the choice of bins is too fine for the initial averaging.
   a. Look at actual bins for each 200m segment in the Argo estimate; can I do better?

3. If we can't actually do the Ferrari & Polzin decomposition; what else can we do?
   a. Groeskamp et al (2020) × gradient gives us an estimate of mesoscale stirring variance production. Argo gives us an estimate of χ. We could look for places where they agree / disagree →
      a. [ ] if they are close eddies are important; does this line up with EKE at surface
      b. [ ] problem is groeskamp et al have everything vary with EKE_surface so...
      c. [ ] Maybe there are locations where eddy variance is larger than finestructure χ

4. Follow up on sampling issues:
   - [ ] Make sure I am getting all argo profiles in the area; not excluding unnecessary ones

5. Could try GO-SHIP sections

* Isopycnal gradient methodologies
** cite:NaveiraGarabato2016

1. ε, χ are averaged in neutral density bins fo 0.08 kg/m³
2. The CTD measurements of θ for that section repeat are bin averaged in the same density intervals, and a cubic spline is fitted to the binned θ values on each isoneutral surface
3. All isoneutral and dianeutral gradients are computed using centered differencing in along-section distance–neutral density space, except for the northernmost and southernmost stations in each section occupation and for density bins adjacent to bins with absent data, for which forward or backward differencing is used.
4. After mapping the θ observations along all sections to a Y‐gn grid, we calculate the θ_m distribution along each transect location by fitting a cubic spline to all the Y‐θ data pairs sampled on each neutral surface. The choice of a cubic spline in this definition is motivated by the continuity of both the curve and its first derivative, which is implicated in the calculation of L_mix (see (3)).

* Paper ideas
- [ ] 0, 140 and thinking about long timescales
- [ ] CTD χpods : large-scale patterns : global section maps + correlations
  - maps of K_T, K_H
- [ ] ACC effort
- [ ] Are K_T and K_H from Argo self-consistent?
- [ ] finestructure / model / data : scott / sylvia / whalen / CPT

* Meetings
** emily 2019-12-09
- [-] eddy diff
  - [X] year 1 funds available
  - [X] I have 1.7FTE -> 1.2FTE
  - [X] subaward status
  - [ ] how to proceed
    - emily
      - [ ] checks data quality of KT
      - [ ] get CTD-χpod data status from jonathan
    - [ ] TODO think about χpod data and do time series stuff
      - [ ] do 0-140

  - Paper ideas; target: 1 paper by December: CTD χpod stuff?
    - [ ] 0, 140 and thinking about long timescales
    - [ ] CTD χpods : large-scale patterns : global section maps + correlations
      - maps of KT, KH
    - [ ] finestructure / model / data
    - [ ]  ACC effort
    - [ ] Are K_T and K_H from Argo self-consistent?
    - [ ] model-data comparison with scott + eddy CPT

- [ ] promotion -> proposals
  - [ ] eq pac chipods
  - [ ] indian ocean chipods

- Indian Ocean review paper
  - [X] need to fix BoB section
  - [X] χpod summary image

* Notes
** MOM6 lecture notes
1. Redi (1982)  - rotate diffusion operator to be along isopycnals
2. Cox (1987) - redi improves things but need horizontal diffusion to get diapycnal fluxes -> fixed by gent mcwilliams
3. griffies 1998 - uses triads (?)
4. groeskamp et al 2019 - emphasize inaccuracy of calculating slopes locally
5. Rotation has issues:
   1. Bleckers et al 1998 cannot guarantee positive definite -> generate local extrema
   2. Griffies 1998 numerical instability
   3. slopes need to be tapered and limited for numerical reasons
6. new epineutral operator appropriate for adiabatic interior ocean, preserves extrema, no need for regularization or tapering
** Things I've learned
1. *Smoothing* cubic splines are a little funky near the edge. Need a "natural" boundary condition that forces curvature to be 0 at edge. NG2016 seems to suffer from this too.
2. ECCO ~RhoAnoma~ is /in-situ/ density anomaly! Argo has potential density.
3. Why ECCO instead of Argo? - deeper than 2000db!
4. ~sw.dist~ needs lon=[-180, 180]!
5. Coarse abyssal ocean resolution means that some density classes are not represented in ECCO.
   - Do I interpolate to finer resolution?
6. Choice of density variable / reference pressure is really important!
   - contours change drastically at depth if referencing to the surface.
   - *this means I average over a different set of observations!*
   - with p06, doing σ_0 works OK. Looking at the WOCE sections, things aren't too different.
   - Neutral density is clearly the way to go.
7. Linear fits to ECCO T along ρ surfaces in the along-transect direction doesn't work. The field has too much curvature. Though could work OK near surface.

** Todo [0/2]
1. [ ] Select region before interpolating in ~read_all_datasets()~
2. [ ] Do something about coarse ECCO resolution at depth

* TAO May 2008 χpod notes

| depth | unit | notes                                     |
|-------+------+-------------------------------------------|
|    14 |  313 | use sensor 1                              |
|    29 |  323 | all bad?                                  |
|    39 |  324 | use sensor 1, T1 drifts low, turb OK      |
|    49 |  318 | all bad/                                  |
|    59 |  325 | use sensor 1                              |
|    69 |  319 | chi2 not good; chi1 low in apr-may2009    |
|    84 |  326 | use sensor 1                              |
|   100 |  320 | hardly any good data, p, acc did not work |
|   124 |  327 |                                           |
|   150 |  321 | bad after apr 21, 2009                    |

* Annual Reports

** 2020
*** Emily email

I  think we  should start  with an email to Nadya today.   Let her know
 a) its  the first the  you have heard this request, and that
 b) it may be  related to the delayed start in October associated with  your transition. Also ask if there  is a website  or template available for its  format.
 c)  (Let her know we weren’t expecting a second increment until the fall.)

More generally being new  to NASA (I am too apart from Kerstin’s NESSF), ask if annual reports are always due at this time of year or  if the timeline  varies by grant/year.  NASA  may be like ONR— everything is due  at once.

Let her know that it will be a scramble to put something together before  the deadline, but that we can try our best. (I am  camping  starting Sunday.)

Let’s chat about a  collection of figures that could  go into the report, likely relying on  the proposal. How much have you started spending on the grant? I don’t think that I have spent much of anything, possibly just started. I had to put in a 1 year extension with UCAR recently, so this may be a failure of your  grants department to pass along correspondence  from NASA. Give Nadya this out in the email.
*** Nadya email
Hi Nadya,

We were very surprised to receive this email today.

Somehow, neither I (as PI) or UCAR's AOR was notified of a deadline for the report.
A complication is that I moved from OSU to UCAR and we ended up resubmitting the proposal through NCAR in April and the money arrived at NCAR at the end of October.
So we were not expecting a second increment until later this fall.

I will work on this ASAP and will email you before July 1.
We are just ramping up work on the project and have been primarily focusing on data QC and updated analysis procedures.

Can you confirm that the template here (https://answers.nssc.nasa.gov/app/answers/detail/a_id/6293) is current and is the expected format for this report?

Thanks,

Deepak

*** Actual report
*Title of the report*: Relating SSHA-derived Eddy Diffusivity to In-situ Estimates from Microstructure and ECCO

*Type of report*: Progress report (year 1)

*Name of the principal investigator*: Deepak A. Cherian

*Period covered by the report*: 08/01/19 - 07/31/20

*Name and address of the recipient's institution*. UNIVERSITY CORPORATION FOR ATMOSPHERIC RESEARCH, 3090 CENTER GREEN DR, BOULDER CO 80301-2252

*Grant number*: 80NSSC19K1234

**** Accomplishments: Start by reminding us what are the major goals and objectives of the project and what did you achieve towards those goals? At first the emphasis will be on reporting activities but as the project progresses you will be reporting specific accomplishments. For example, describe major activities; significant results, major findings, developments, or conclusions (both positive and negative); and key outcomes or other achievements. Include a discussion of stated goals not met.

The major goal of this project is to combine microstructure measurements with an estimate of mean density gradients in the ocean to yield an estimate of eddy diffusivty.
- These estimates will be compared to existing estimates from SSH satellite data, the ECCO model and the Argo array.
- We expect these measurements to yield an independent estimate of a high-order quantity that is necessary for models such as ECCO but whose value is relatively under-constrained by observations.

We have two kinds of microstructure measurements:
  1. basin-wide sections from GO-SHIP cruises
  2. Moored microstructure platform (χpods) on a number of moorings in the equatorial oceans.

Currently we are working on preliminary data analysis and QC of both types of measurements.
  - Our preliminary results presented in the proposal relied on the GO-SHIP data along section P16 (east-west through the Pacific at 32°S) and a crude estimate of mean temperature gradient along isopycnals from the ECCO climatology.
  - We have been working to update this estimate with better analysis procedures and better quality controlled data.
  - Co-I Shroyer at OSU has been working on QC-ing the P-16 section as well as processing more data from the GO-SHIP sections (only P16 has been processed to date.)
  - PI Cherian has been working on better ways to estimate mean property gradients along isopycnal surfaces from a number of data products (Argo climatology, MIMOC climatology, ECCO climatology).
  - In addition, Cherian has been updating analysis software to use the moored turbulence data from the TAO mooring at 0N, 140W.

PI Cherian is currently funded by NOAA to work on aspects of parameterized turbulence in high resolution models of the tropical Pacific.
  - As part of this work, a realistically-forced 1/20° simulation of tropical Pacific was conducted by Dr. Scott Bachman (NCAR). Cherian & Bachman worked to set up high-frequency sampling of parameterized turbulence quantities in the simulation at the mooring locations in the tropical Pacific with moored turbilence data. We expect joint analysis of the simulation and in-situ observations to yield insights that may not be possible without the model output.

**** How have the results been disseminated: For example, a list of publications that have appeared as a result of the award. Of course all publications should acknowledge NASA support, including the name of the program, and the grant number(s).

We are at the preliminary analysis and data quality control stage of the project so we have no publishable results at the moment. We expect to be working on a publication by the end of this year.

**** Future plans: if this is not your final report, what are you planning to do next? Is it different than what was in the original proposal? That's OK, but please explain a bit.

Our main goal for the next 2-3 months is to:
  - process more GO-SHIP sections
  - generate a high-quality estimate of mean property gradients along isopycnal surfaces fom a number of products.
  - Our primary goal for the fall is a publication summarizing eddy diffusivity estimates from all sections.
Simultaneously we will be refining our estimation procedure to handle moored data with a goal of publishing eddy diffusivity time series in Summer 2021.

* ECCO
** Gael's email
** running ecco
- cd build;  ../../../tools/genmake2 -mods=../code -optfile=../linux_amd64_ifort+mpi_yellowstone -mpi
** ECCO configuration
** GM/Redi notes
For ECCO:
- implicitDiffusion = true
- GM_AdvForm = TRUE, GM_InMomAsStress = FALSE, GM_AdvSeparate=False
- Kgm ≠ Kredi
- config file:
    viscAr=0.5E-4,
    #
     viscAh=1.E0,
     viscAhGrid=2.E-2,
    # viscAh=2.0e4,
    #
     diffKhT=1.E1,
     diffKrT=1.E-5,
     diffKhS=1.E1,
     diffKrS=1.E-5,
    #
    ### diffKrBL79surf=0.1E-4,
    ### diffKrBL79deep=1.0E-4,
     bottomDragQuadratic = 0.001,
    #when using ggl90
     ivdc_kappa=10.,
     implicitDiffusion=.TRUE.,
     implicitViscosity=.TRUE.,
- stdout:
    (PID.TID 0000.0001) GM_AdvForm =     /* if FALSE => use SkewFlux Form */
    (PID.TID 0000.0001)                   T
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_InMomAsStress = /* if TRUE => apply as Eddy Stress */
    (PID.TID 0000.0001)                   F
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_AdvSeparate = /* Calc Bolus & Euler Adv. separately */
    (PID.TID 0000.0001)                   F
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_ExtraDiag =   /* Tensor Extra Diag (line 1&2) non 0 */
    (PID.TID 0000.0001)                   T
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_isopycK =    /* Background Isopyc. Diffusivity [m^2/s] */
    (PID.TID 0000.0001)                 1.000000000000000E+03
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_skewflx*K =  /* Background GM_SkewFlx Diffusivity [m^2/s] */
    (PID.TID 0000.0001)                 0.000000000000000E+00
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_advec*K =    /* Backg. GM-Advec(=Bolus) Diffusivity [m^2/s]*/
    (PID.TID 0000.0001)                 1.000000000000000E+03
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_Kmin_horiz = /* Minimum Horizontal Diffusivity [m^2/s] */
    (PID.TID 0000.0001)                 1.000000000000000E+02
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_Visbeck_alpha = /* Visbeck alpha coeff. [-] */
    (PID.TID 0000.0001)                 0.000000000000000E+00
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_Small_Number =  /* epsilon used in slope calc */
    (PID.TID 0000.0001)                 9.999999999999999E-21
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_slopeSqCutoff = /* Slope^2 cut-off value */
    (PID.TID 0000.0001)                 1.000000000000000E+08
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_taper_scheme =  /* Type of Tapering/Clipping scheme */
    (PID.TID 0000.0001)               'stableGmAdjTap                          '
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_maxSlope =  /* Maximum Slope (Tapering/Clipping) */
    (PID.TID 0000.0001)                 4.000000000000000E-03
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_facTrL2dz = /* Minimum Trans.Layer Thick. (factor of dz) */
    (PID.TID 0000.0001)                 1.000000000000000E+00
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_facTrL2ML = /* Max.Trans.Layer Thick. (factor of MxL Depth)*/
    (PID.TID 0000.0001)                 5.000000000000000E+00
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_maxTransLay = /* Maximum Transition Layer Thickness [m] */
    (PID.TID 0000.0001)                 5.000000000000000E+02
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_UseBVP = /* if TRUE => use bvp a la Ferrari et al. (2010) */
    (PID.TID 0000.0001)                   F
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_BVP_ModeNumber = /* Vertical mode number for BVP wave speed */
    (PID.TID 0000.0001)                       1
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_BVP_cMin = /* Minimum wave speed for BVP [m/s] */
    (PID.TID 0000.0001)                 1.000000000000000E-01
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) GM_useSubMeso = /* if TRUE => use Sub-Meso param. (B.Fox-Kemper) */
    (PID.TID 0000.0001)                   F
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) subMeso_Ceff = /* efficiency coeff. of Mixed-Layer Eddies [-] */
    (PID.TID 0000.0001)                 7.000000000000001E-02
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) subMeso_invTau = /* inverse of Sub-Meso mixing time-scale [/s] */
    (PID.TID 0000.0001)                 2.000000000000000E-06
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) subMeso_LfMin = /* minimum length-scale "Lf" [m] */
    (PID.TID 0000.0001)                 1.000000000000000E+03
    (PID.TID 0000.0001)     ;
    (PID.TID 0000.0001) subMeso_Lmax = /* maximum grid-scale length [m] */
    (PID.TID 0000.0001)                 1.100000000000000E+05
    (PID.TID 0000.0001)     ;

SO!
- GM vertical diffusion is in DFrI_TH; it's added to KappaRx from vertical mixing
- Kwz, Kwy terms are in DFrE_TH
- Lateral terms are lumped in with diffKh, diffK4 contributions in dFxE_TH, dFyE_TH

- http://mailman.mitgcm.org/pipermail/mitgcm-support/2013-November/008616.html
  #+begin_quote
The isopycnal diffusion (Redi part) contribution is put into the diffusive flux, splitted into the 3 directions and, if using implicitDiffusion=.TRUE., with a distinction between explicit vertical flux (which contains the contribution Kwx d.T/dx + Kwy d/T/dy) and the implicit vertical flux (which contains the contribution Kwz d.T/dz).
For instance, for temperature (but it's available for any tracer):
   112 |DFrE_TH | 15 |       |WM      LR|degC.m^3/s      |Vertical Diffusive Flux of Pot.Temperature (Explicit part)
   113 |DFxE_TH | 15 |   114 |UU      MR|degC.m^3/s      |Zonal      Diffusive Flux of Pot.Temperature
   114 |DFyE_TH | 15 |   113 |VV      MR|degC.m^3/s      |Meridional Diffusive Flux of Pot.Temperature
   115 |DFrI_TH | 15 |       |WM      LR|degC.m^3/s      |Vertical Diffusive Flux of Pot.Temperature (Implicit part)
And if using the Skew-Flux form, the GM part (which double Kwx & Kwy and cancel Kuz and Kvz if K_GM = K_iso ) will also fall into these diffusive flux diagnostics.

With the advective form of GM ( GM_AdvForm=.TRUE.), and assuming the default GM_AdvSeparate=.FALSE. is used, the eulerian mean and the bolus transport are combined together to form the residual mean which is used to advect all tracers. And in this case, the GM contribution to the tracer tendency is part of the advective flux diagnostics, e.g. for temperature:
   109 |ADVr_TH | 15 |       |WM      LR|degC.m^3/s      |Vertical   Advective Flux of Pot.Temperature
   110 |ADVx_TH | 15 |   111 |UU      MR|degC.m^3/s      |Zonal      Advective Flux of Pot.Temperature
   111 |ADVy_TH | 15 |   110 |VV      MR|degC.m^3/s      |Meridional Advective Flux of Pot.Temperature
Note that these diagnostics match exactly what the model computes since they come directly out of the model advection subroutines. But no distinction is made between the advective flux due to the eulerian mean and the one due to the bolus transport (hard to define anyway when the advection scheme is non-linear regarding the velocity).

For this reason, but only available for temperature (sorry), there is an approximate estimation of the Bolus transport of temperature (consistent with a centered in time and space advection scheme, like tempAdvScheme=2) which is diagnose (in pkg/gmredi/gmredi_xtransport.F & pkg/gmredi/gmredi_ytransport.F) and available with the advective form:
   209 |GM_ubT  | 15 |   210 |UUr     MR|degC.m^3/s      |Zonal Mass-Weight Bolus Transp of Pot Temp
   210 |GM_vbT  | 15 |   209 |VVr     MR|degC.m^3/s      |Meridional Mass-Weight Bolus Transp of Pot Temp

An other alternative, since all Redi (+GM if skewFlux form) matrix coefficient are available
as diagnostics:
   197 |GM_Kux  | 15 |   198 |UU P    MR|m^2/s           |K_11 element (U.point, X.dir) of GM-Redi tensor
   198 |GM_Kvy  | 15 |   197 |VV P    MR|m^2/s           |K_22 element (V.point, Y.dir) of GM-Redi tensor
   199 |GM_Kuz  | 15 |   200 |UU      MR|m^2/s           |K_13 element (U.point, Z.dir) of GM-Redi tensor
   200 |GM_Kvz  | 15 |   199 |VV      MR|m^2/s           |K_23 element (V.point, Z.dir) of GM-Redi tensor
   201 |GM_Kwx  | 15 |   202 |UM      LR|m^2/s           |K_31 element (W.point, X.dir) of GM-Redi tensor
   202 |GM_Kwy  | 15 |   201 |VM      LR|m^2/s           |K_32 element (W.point, Y.dir) of GM-Redi tensor
   203 |GM_Kwz  | 15 |       |WM P    LR|m^2/s           |K_33 element (W.point, Z.dir) of GM-Redi tensor
would be to calculate (offline) an approximate evaluation (neglecting time correlation between tracer gradient and Redi-GM matrix coeff) of gmredi flux, base on the time-mean tracer gradient and the time-mean GM-Redi coefficient.

Note that, but again for temperature only, some gmredi flux are available as diagnostics:
   206 |GM_KuzTz| 15 |   207 |UU      MR|degC.m^3/s      |Redi Off-diagonal Temperature flux: X component
   207 |GM_KvzTz| 15 |   206 |VV      MR|degC.m^3/s      |Redi Off-diagonal Temperature flux: Y component
   208 |GM_KwzTz| 15 |       |WM      LR|degC.m^3/s      |Redi main-diagonal vertical Temperature flux
  #+end_quote
- http://mailman.mitgcm.org/pipermail/mitgcm-support/2017-January/010825.html
  #+begin_quote
For any tracer, when using pkg/gmredi, it adds to vertical fluxes
two diffusive components that are proportional to horizontal tracer gradient
(Kwx & Kwy components of the GM-Redi tensor) and these components are always
evaluated explicitly (i.e., forward in time) since an implicit implementation
would be far too complicated and expensive.
These terms (Kwx & Kwy) are due to the Redi tensor but are increased by some GM
contributions when using the Skew-flux form (GM_AdvForm = .FALSE., i.e, the default).

The vertical flux 3rd component from GM-Redi is due to Kwz tensor component
and is easy to process implicitly (vertical flux function of vertical gradient)
like any vertical diffusivity contribution; this is the case when implicitDiffusion=.TRUE.

In term of diagnostics, with useGMRedi=TRUE,
1) the first 2 components (from Kwx & Kwy) are accounted for in diagnostics "DFrE_???";
2) the 3rd component (from Kwz) is either
    added to "DFrE_???" when using implicitDiffusion=.False. (i.e., the default)
  or
   accounted for in diagnostics "DFrI_???" when using implicitDiffusion=.True.
istent with tracer time-stepping ( forward / backward
time-stepping = explicit / implicit ).
  #+end_quote
