# Book settings
title: Eddy Diffusivity
author: Deepak Cherian
logo: logo.png

repository:
  url                       : https://github.com/dcherian/eddydiff  # The URL to your book's repository
  path_to_book              : "notebooks/"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

html:
  use_repository_button: true
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  extra_footer: |
      <div>
      <script data-goatcounter="https://count.cherian.net/count"
              async src="count.js"></script>
      </div>

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: 'off'

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
