#+title: Testing modelled mesoscale stirring using microscale observations
#+latex_class: dcarticle
#+AUTHOR: D.A. Cherian, Y. Guo, F.O. Bryan, E.L. Shroyer
#+OPTIONS: toc:nil broken-links:mark
#+latex_header_extra:  \usepackage{svg}

* Introduction

#+CAPTION: Schematic of approximate tracer variance pathways
#+LABEL: fig:schematics
[[file:../images/schematics-edited.pdf]]

  Intro points
  - representing mesoscale eddy stirring in models

** Tracer variance pathways
We rely on the analytical framework of [[cite:&Ferrari2005]] and [[cite:&Garrett2001a]]. Begin with a triple decomposition of the temperature fields
\begin{equation}
    T = T_m + T_e + T_t
\end{equation}
where the subscripts $m$, $e$ and $t$ are loosely identified with the "mean", "mesoscale eddy", and "turbulence" scales.
- some qualitative text about scales/features in each term
- something about submesoscale

Define the "large-scale averaging operator" $⟨⟩$ that filters out the "eddy" and "turbulence" so that $⟨T⟩ = T_m$ and an intermediate scale averaging operator $\widetilde{\phantom{...}}$ that filters out the "turbulence" so that $\widetilde{T} = T_m + T_e$.
Ferrari & Polzin (2005) follow Garrett (1992) to derive the variance budget equations for $⟨T_e^2⟩$ and $⟨T_t^2⟩$.
Assuming stationarity, and homogeneity, and /a priori/ ignoring the triple correlation term, we can write the approximate equations
\begin{align}
⟨u_eT_e⟩ ⋅ ∇T_m - ⟨\widetilde{u_t T_t} ⋅ ∇T_e⟩ &\approx 0 \\
⟨\widetilde{u_tT_t} ⋅ ∇ (T_m  + T_e)⟩ &\approx - \frac 12 ⟨\widetilde{χ}⟩; \qquad χ = κ_T |∇T_t|^2
\end{align}
Here $χ$ represents the instantaneous rate of dissipation of temperature variance and $κ_T$ is the molecular diffusivity of temperature.

The first equation, derived from that for mesoscale variance $⟨T_e^2⟩$, states that the mesoscale scale field generates variance by the stirring of the mean and this variance cascades down to the microscale turbulence through the "scale transoframtion term" $χ^e ≡ ⟨\widetilde{u_t T_t} ⋅ ∇T_e⟩$.
The second equation, derived from that for microscale variance $⟨T_t^2⟩$, states that the microscale turbulence stirs the combination of the mean and eddy fields $(T_m  + T_e)$ to generate variance that is eventually dissipated at the molecular scale at the rate $χ$.
The scale transformation term $χ^e$ has opposite sign in the two equations highlighting its role in linking the mesoscale and microscale.
See an illustrative summary of these pathways from cite:Garrett2001a in Figure [[fig:schematics]]a.

Adding the two equations yields the approximate balance,
\begin{equation}
⟨\widetilde{u_tT_t}⟩ ⋅ ∇ T_m  + ⟨\widetilde{u_e T_e}⟩ ⋅ ∇ T_m \approx - \frac 12 ⟨χ⟩
\end{equation}
that is the variance dissipated at the molecular scale is approximately generated by the stirring of the mean field $T_m$ by the mesoscale and microscale turbulence.
A large number of approximations are required to get to this point, but this framework has value in qualitatively describing the nature of variance cascades in the ocean [[citep:&Garrett2001a;&Ferrari2005;&Spingys2021;&NaveiraGarabato2016]].

** Variance pathways as a model diagnostic
We can further simplify this budget assuming that $u_t$ is isotropic but $∂_zT_m \gg ∇^hT_m$ so $⟨\widetilde{u_tT_t}⟩ \approx ⟨\widetilde{w_tT_t}⟩$, and that mesoscale scale stirring acts in the horizontal along isopycnals (CITATION) so that $⟨\widetilde{u_e T_e}⟩ ⋅ ∇ T_m \approx  ⟨\widetilde{u^h_e T_e}⟩ ⋅ ∇^h T_m$
\begin{equation}
\label{eq:final}
⟨\widetilde{w_tT_t}⟩ ⋅ ∂_z T_m  + ⟨\widetilde{u^h_e T_e}⟩ ⋅ ∇^h T_m \approx - \frac 12 ⟨χ⟩
\end{equation}

For a mesoscale resolving model, the second term is resolved and we can qualitatively identify the "turbulence" as representing subgrid scale motions whose effect on the mean scales is parameterized.
For coarser models where even the mesoscale is parameterized, $χ^e$ is commonly modelled by an along-isopycnal cite:&Redi1982 diffusivity.
- literature for parameter values being relatively unconstrained
- recent eddy mixing CPT work
- links to mesoscale variance budgets

cite:&Ferrari2005 estimate the turbulent stirring term and $⟨χ⟩$ in \eqref{eq:final} using microstructure profiles collected as part of the North Atlantic Tracer Release Experiment (NATRE, [[citealp:&Ledwell1998;&St.Laurent1999]]) (ADD FIGURE WITH MAP).
They interpret the residual difference between the two terms as the scale transformation term and as  evidence for the effectiveness of eddy stirring in generating temperature variance that determines the finescale structure of the $T-S$ relation.
Here we go a step further, and use that interpretation as a starting hypothesis.

We ask whether the estimated mesoscale stirring term in a mesoscale-resolving model, and the parameterized variance dissipated by parameterize cite:&Redi1982 diffusion in a coarse 1° model compare well against the estimated magnitude of the scale transformation term using the NATRE observations and the cite:&Ferrari2005 methodology.
We compare resolved and parameterized mesoscale eddy stirring to an observational estimate using the variance production rate as a metric.
This rate is a direct output of the lateral diffusivity scheme, so the comparison is /direct/ in the sense of cite:&Large1999.
We choose $χ$ rather than an eddy diffusivity $K_e$ to avoid further uncertainties associated with defining the mean gradient $∇^h T_m$, but this means that errors in simulating $T_m$ affect the interpretation (Section XXX).

The analysis presented here is novel in that it utilizes realistic primitive equation models in production configurations with realistic forcing.
In this way, it differs from the work of cite:&Smith2009 who use a 1km quasigeostrophic model to support the interpretation that mesoscale eddy stirring is the major contributor to the scale transformation term in the NATRE region.

* Datasets
** TODO CTD Χpod estimates from Obs paper :noexport:
** NATRE microstructure dataset
The core microstructure dataset used in this analysis is that from the North Atlantic Tracer Release Experiment (NATRE, [[citealp:&Ledwell1998;&St.Laurent1999]]), collected in April 1992 using the Woods Hole Oceanographic Institution High Resolution Profiler (HRP: [[cite:&Schmit1988]]).
We use vertical profiles from the "large scale survey": approximately 100 profiles down to 2000dbar collected in a 400km x 400km box (26.5W-31W; 24N-28N) as a 10x10 grid at approximately 0.5° (44.4km) spacing.
These profiles contain quality-controlled estimates of temperature, salinity, dissipation rate of temperature variance $χ$, and dissipation rate of turbulence kinetic energy $ε$ at 0.5dbar spacing.
The dataset is available publicly in the NSF Microstructure database (ADD LINK) [[cite:&Waterhouse2014]].

** Observational estimates of $K_e$
We use two observational estimates of Redi diffusivity $K_e$, both of which use mixing length theory to express diffusivity as
\begin{equation}
    K \sim C \, U_e \, L_e
\end{equation}
where $C$ is a constant, $U_e$ is an appropriate velocity scale, and $L_e$ is a length scale.
The first estimate, from \cite:&Cole2015, uses a root mean square velocity $u_{rms} = \sqrt{⟨u'^2 + v'^2⟩}$ from the ECCO2 state estimate for $U_e$.
They estimate a mixing length scale $L_e$ using salinity anomalies on an isopycnal.
\begin{equation}
L_e = \frac{\sqrt{⟨S'S'⟩}}{⟨|∇{S}|⟩}
\end{equation}
Primed quantities are defined as the anomaly relative to a 1 year running average of that quantity ${q}$, so $q' = q - {q}$.
Salinity on an isopycnal surface $S$ is estimated using the mapped Argo climatology of cite:&Roemmich2009.
The constant $C$ is chosen to be 0.16 following cite:&Wunsch1999;&Klocker2014

The second estimate of $K_e$, from cite:&Groeskamp2020a, estimates $U_e$ as the root mean square of the geostrophic velocity $u_{rms}$ (WHERE), and $L_{e}$ as the first Rossby radius of deformation calculated as the eigenvalue associated with the first baroclinic mode.
In addition they account for a depth dependence of $K$ that accounts the suppression of eddy stirring in the presence of a mean flow (CITATIONS).

\begin{equation}
K^{G2020} = \frac{C u_{rms}(z) L_{mix}}{1 + k^2 γ^{-2} (c_w - U(z))^2}
\end{equation}

Depth dependence arises from the depth dependence of the mean flow $U(z)$ and depth-dependence of the eddy velocity scale $u_{rms} (z)$.
The vertical structure of $u_{rms}$ is determined by extrapolating the surface EKE downwards using a vertical mode structure estimated using the "first surface mode" (CITATION).
See [[cite:&Groeskamp2020a]] for more details.

** Simulations
We examine the variance pathways in a suite of global model integrations.
*** POP 1/10° model
[[cite:&Guo2022]] present a temperature variance budget analysis for an interannually forced simulation using the Parallel Ocean Program Version 2 (POP2, citealp:&pop) component of the Community Earth System Model version 2 cite:&CESM2 with a grid of nominal 1/10° horizontal spacing, and 62 vertical levels with spacings between 10m and 250m.
The model is forced using the Japanese 55-year Reanalysis dataset (JRA55, [[citealp:&jra55]]).
This simulation uses the K-profile parameterization scheme (KPP, citealp:&Large1994) to parameterize vertical mixing, and biharmonic viscosity and diffusivity to represent horizontal stirring and eventual mixing.
Biharmonic viscosity and diffusivity values vary with the cube of the grid spacing and have equatorial values of \SI{2.7e10}{\meter^4\per\second} and \SI{3e9}{\meter^4\per\second}, respectively.

- add KPP parameters
*** POP 1°
We will also use a workhorse configuration of the CESM ocean component POP2 at a nominal resolution of 1°, and 40 vertical levels with spacing XXX.
At this coarse resolution, the model does not resolve mesoscale eddies and relies on a Redi diffusivity along isopycnals to represent along-isopycnal eddy stirring.
This model too uses the KPP scheme with parameters...
- lateral mixing parameters?
- Mention KPP
- Mention vertical grid details
*** TODO MOM 2/3°
*** TODO ECCO?

* Results
TODO:
- Add med outflow maps : S along isopycnal

** Observational estimates
<<sec:obs>>

** Diagnosing a mesoscale resolving simulation
- Garrett diagram specialized to POP 1/10°
- something about it being a z-coordinate analysis.

The 1/10° simulation explicitly resolves mesoscale eddies, and therefore eddy stirring along isopycnals.
Thus the model resolves the mean → mesoscale pathway.
However, this model is too coarse to convert the horizontal variability to vertical variability to be dissipated by the vertical mixing scheme.
The vertical spacings are approximately \SI{100}{m} (DOUBLE CHECK THIS) at the depth range of spicy variability.
So instead, the variance generated by mesoscale stirring is cascaded down to the grid-scale where it is dissipated by the biharmonic lateral diffusivity.
In this way, the biharmonic diffusivity is not necessary purely for numerical stability reasons but also to represent the variance pathway from the mesoscale → microscale → molecular scale diffusion.

With this framework we can now reinterpret the terms in the analysis of cite:&Guo2022.
In the top ~800m of the water column, spiciness is low.
Here lateral eddy stirring of the $T$ and $S$ fields generates density anomalies, and potential energy anomalies ("eddy potential energy" EPE).
The EPE is then converted to eddy kinetic energy (EKE).
Such process are parameterized in coarser models through the cite:&Gent1995 scheme.

Between ~800m and 1500m, the water column is spicy.
Here, eddy stirring is effective at generated $T$ and $S$ anomalies that are density-compensated and have almost no EPE.
Such compensated is variance is cascaded down to the grid scale for dissipation by a lateral diffusivity.
So the budget indicates that the lateral dissipation balances the lateral stirring term.

As rationalized earlier, the lateral stirring term in this decomposition is effectively the mesoscale → microscale conversion term and can be directly compared to the residual computed using the microstructure estimates (Section ref:sec:obs)

We find remarkable agreement between the two in that the simulated variance dissipation is within the error bars of the residual from the observations.
Note that the only comparable previous analysis of cite:&Smith2009 used a quasigeostrophic model at 1km resolution, while this is a primitive equation simulation.

** Diagnosing coarser simulations
At coarser horizontal grid spacings, models cannot, or only partially, resolve the mean -> mesoscale pathway.
Here the effect of lateral stirring along isopycnals in spicy regions is represented using a cite:&Redi1982 diffusivity applied along isopycnals.
So we can estimate the variance dissipated by the application of a along-isopycnal diffusivity to the microscale residual estimated in Section [[sec:obs]].

Doing so is complicated by the fact that such models are usually deficient in other areas.
One deficiency of relevance is a lack of fidelity in simulating the Mediterranean outflow (Figure XXX).
In variance budget terms, if the model is unable to maintain the along-isopycnal water mass contrast it is initialized with, then it is not going to replicate the right $χ^e$, even if it applied the right diffusivities.

So we choose to diagnose the spin up of a coarse model configuration.

*** Diagnosing POP 1° spinup.
- but not strengthening it at the right rate?
- compare med tongue / mean state to 1/10
- did the med tongue move?

This model is initialized with the World Ocean Atlas 2018 (CITATION) and zero velocities.

Being initialized from observations, the initial along isopycnal gradients are quite good when compared to observations.
We see that $χ^e$ compares quite well to the microstructure residual at 1200dbar.
So when a relatively accurate along-isopycnal gradient exists, the right amount of variance is dissipated.

This suggests that at least in this region, the model is not overly diffusive but instead has a problem maintaining the water-mass contrast along isopycnals through the advection of the Mediterranean outflow.

In other words, errors in the variance budgets arise from errors in the simulation of the mean state, than in errors in parameterizing the mesoscale in the NATRE region.
*** MOM 2/3°
*** TODO ECCO v4.3 differences with K_e adjustments?
* Discussion
* Acknowledgements
- Keith Lindsay
* References
[[bibliography:/Users/dcherian/work/Papers/bibtexLibrary.bib]]
bibliographystyle:elsarticle-harv
